const realEstateData = [
    {
        imgUrl: 'https://via.placeholder.com/250',
        title: 'Luxury Villa in Andorra la Vella',
        price: '$3,500,000',
        description: 'A stunning 4-bedroom villa located in the heart of Andorra la Vella, offering panoramic mountain views and modern amenities.',
        address: 'Andorra la Vella, Andorra',
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: '3500',
        yearBuilt: 2018,
        propertyType: 'Villa',
        country: 'Andorra',
        city: 'Andorra la Vella',
        priceRange: '300000-500000',
        squareFeetRange: '3000-5000',
        yearBuiltRange: '2011-2020',
        parking: 'Available',
        garden: 'Yes',
        flooring: 'Wood',
        publicTransport: 'Close',
        elevator: 'Available',
        furnishing: 'Furnished',
        view: 'Mountain',
        airConditioning: 'Available',
        heating: 'Central',
        pool: 'Available',
        balcony: 'Available',
        roof: 'Flat',
        security: 'Available',
        schools: 'Yes',
        internet: 'Available',
        gym: 'Available',
        storage: 'Available',
        shopping: 'Close',
        hospital: 'Yes',
        park: 'Yes',
        beach: 'Close'
    },
    {
        imgUrl: 'https://via.placeholder.com/250',
        title: 'Modern Apartment in Kabul',
        price: '$500,000',
        description: 'A spacious 2-bedroom apartment located in the city center of Kabul, offering modern amenities and a great view of the city.',
        address: 'Kabul, Afghanistan',
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: '1200',
        yearBuilt: 2020,
        propertyType: 'Apartment',
        country: 'Afghanistan',
        city: 'Kabul',
        priceRange: '0-1000000',
        squareFeetRange: '1000-2000',
        yearBuiltRange: '2021+',
        parking: 'Available',
        garden: 'No',
        flooring: 'Tile',
        publicTransport: 'Close',
        elevator: 'Not Available',
        furnishing: 'Unfurnished',
        view: 'City',
        airConditioning: 'Not Available',
        heating: 'Individual',
        pool: 'Not Available',
        balcony: 'Not Available',
        roof: 'Sloped',
        security: 'Not Available',
        schools: 'Yes',
        internet: 'Available',
        gym: 'Not Available',
        storage: 'Not Available',
        shopping: 'Far',
        hospital: 'Yes',
        park: 'No',
        beach: 'Far'
    },
    {
        imgUrl: 'https://via.placeholder.com/250',
        title: 'Spacious House in Tirana',
        price: '$800,000',
        description: 'A beautiful 3-bedroom house with a garden, located in a quiet area of Tirana, offering a modern design and comfort.',
        address: 'Tirana, Albania',
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: '2500',
        yearBuilt: 2015,
        propertyType: 'House',
        country: 'Albania',
        city: 'Tirana',
        priceRange: '500000-1000000',
        squareFeetRange: '2000-3000',
        yearBuiltRange: '2011-2020',
        parking: 'Available',
        garden: 'Yes',
        flooring: 'Wood',
        publicTransport: 'Far',
        elevator: 'Not Available',
        furnishing: 'Furnished',
        view: 'Park',
        airConditioning: 'Available',
        heating: 'Central',
        pool: 'Not Available',
        balcony: 'Available',
        roof: 'Flat',
        security: 'Available',
        schools: 'Yes',
        internet: 'Available',
        gym: 'Available',
        storage: 'Not Available',
        shopping: 'Close',
        hospital: 'Yes',
        park: 'Yes',
        beach: 'Far'
    },
    {
        imgUrl: 'https://via.placeholder.com/250',
        title: 'Luxury Apartment in Algiers',
        price: '$1,200,000',
        description: 'A luxurious 3-bedroom apartment offering a beautiful view of the Mediterranean Sea, located in the heart of Algiers.',
        address: 'Algiers, Algeria',
        bedrooms: 3,
        bathrooms: 3,
        squareFeet: '2800',
        yearBuilt: 2022,
        propertyType: 'Apartment',
        country: 'Algeria',
        city: 'Algiers',
        priceRange: '1000000-2000000',
        squareFeetRange: '2000-3000',
        yearBuiltRange: '2021+',
        parking: 'Available',
        garden: 'No',
        flooring: 'Marble',
        publicTransport: 'Close',
        elevator: 'Available',
        furnishing: 'Furnished',
        view: 'Sea',
        airConditioning: 'Available',
        heating: 'Central',
        pool: 'Available',
        balcony: 'Available',
        roof: 'Flat',
        security: 'Available',
        schools: 'No',
        internet: 'Available',
        gym: 'Available',
        storage: 'Available',
        shopping: 'Close',
        hospital: 'No',
        park: 'No',
        beach: 'Close'
    }
];
