const realEstateData = [
    {
        "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-1.png",
        "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-2.png",
        "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-3.png",
        "title": "Luxury Villa in Paris",
        "price": "$2,500,000",
        "description": "A stunning 6-bedroom villa with panoramic views of Paris, featuring luxury amenities.",
        "address": "Paris, France",
        "bedrooms": 6,
        "bathrooms": 5,
        "squareFeet": "7500",
        "yearBuilt": "2020",
        "propertyType": "Villa",
        "country": "France",
        "city": "Paris",
        "priceRange": "2,000,000 - 3,000,000",
        "squareFeetRange": "7000 - 8000 sq ft",
        "yearBuiltRange": "2020+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Modern Apartment in Berlin",
        "price": "$550,000",
        "description": "A stylish 3-bedroom apartment located in the heart of Berlin with contemporary features.",
        "address": "Berlin, Germany",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "1500",
        "yearBuilt": "2018",
        "propertyType": "Apartment",
        "country": "Germany",
        "city": "Berlin",
        "priceRange": "500,000 - 600,000",
        "squareFeetRange": "1400 - 1600 sq ft",
        "yearBuiltRange": "2017 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "Street",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Yes",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Beachfront Apartment in Barcelona",
        "price": "$950,000",
        "description": "A beautiful 2-bedroom beachfront apartment offering stunning views of the Mediterranean.",
        "address": "Barcelona, Spain",
        "bedrooms": 2,
        "bathrooms": 2,
        "squareFeet": "1200",
        "yearBuilt": "2015",
        "propertyType": "Apartment",
        "country": "Spain",
        "city": "Barcelona",
        "priceRange": "900,000 - 1,000,000",
        "squareFeetRange": "1000 - 1300 sq ft",
        "yearBuiltRange": "2015+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Sea",
        "airConditioning": "Available",
        "heating": "Individual",
        "pool": "Available",
        "balcony": "Yes",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Luxury Loft in Amsterdam",
        "price": "$1,800,000",
        "description": "A chic 4-bedroom loft in Amsterdam with an industrial design and high-end amenities.",
        "address": "Amsterdam, Netherlands",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "3000",
        "yearBuilt": "2019",
        "propertyType": "Loft",
        "country": "Netherlands",
        "city": "Amsterdam",
        "priceRange": "1,700,000 - 2,000,000",
        "squareFeetRange": "2800 - 3200 sq ft",
        "yearBuiltRange": "2017 - 2020",
        "parking": "Available",
        "garden": "No",
        "flooring": "Concrete",
        "view": "Canal",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Yes",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Penthouse in London",
        "price": "$3,000,000",
        "description": "A luxurious penthouse in central London with amazing views of the city skyline.",
        "address": "London, United Kingdom",
        "bedrooms": 5,
        "bathrooms": 4,
        "squareFeet": "5000",
        "yearBuilt": "2022",
        "propertyType": "Penthouse",
        "country": "United Kingdom",
        "city": "London",
        "priceRange": "2,500,000 - 3,500,000",
        "squareFeetRange": "4500 - 5500 sq ft",
        "yearBuiltRange": "2021+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "City",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Charming Cottage in Edinburgh",
        "price": "$650,000",
        "description": "A quaint 3-bedroom cottage with a picturesque garden and cozy interior, located in Edinburgh.",
        "address": "Edinburgh, Scotland",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "1500",
        "yearBuilt": "2010",
        "propertyType": "Cottage",
        "country": "Scotland",
        "city": "Edinburgh",
        "priceRange": "600,000 - 700,000",
        "squareFeetRange": "1400 - 1600 sq ft",
        "yearBuiltRange": "2010+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Garden",
        "airConditioning": "Not Available",
        "heating": "Individual",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Sloped",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Not Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Contemporary Flat in Milan",
        "price": "$750,000",
        "description": "A sleek 2-bedroom apartment in Milan, offering modern design and a prime city location.",
        "address": "Milan, Italy",
        "bedrooms": 2,
        "bathrooms": 1,
        "squareFeet": "1000",
        "yearBuilt": "2017",
        "propertyType": "Apartment",
        "country": "Italy",
        "city": "Milan",
        "priceRange": "700,000 - 800,000",
        "squareFeetRange": "900 - 1100 sq ft",
        "yearBuiltRange": "2015 - 2020",
        "parking": "Not Available",
        "garden": "No",
        "flooring": "Tile",
        "view": "Street",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Not Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "No"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Elegant Townhouse in Brussels",
        "price": "$1,100,000",
        "description": "A stylish 4-bedroom townhouse in central Brussels with a spacious layout and beautiful interior.",
        "address": "Brussels, Belgium",
        "bedrooms": 4,
        "bathrooms": 3,
        "squareFeet": "2500",
        "yearBuilt": "2015",
        "propertyType": "Townhouse",
        "country": "Belgium",
        "city": "Brussels",
        "priceRange": "1,000,000 - 1,200,000",
        "squareFeetRange": "2400 - 2600 sq ft",
        "yearBuiltRange": "2015+",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Wood",
        "view": "Street",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Not Available",
        "balcony": "Yes",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
        "imgUrl": "https://via.placeholder.com/250",
        "title": "Historic Property in Rome",
        "price": "$2,000,000",
        "description": "A beautiful 3-bedroom historic property located near the Colosseum, blending old-world charm and modern amenities.",
        "address": "Rome, Italy",
        "bedrooms": 3,
        "bathrooms": 2,
        "squareFeet": "3000",
        "yearBuilt": "1890",
        "propertyType": "Historical",
        "country": "Italy",
        "city": "Rome",
        "priceRange": "1,800,000 - 2,200,000",
        "squareFeetRange": "2800 - 3200 sq ft",
        "yearBuiltRange": "1800 - 1900",
        "parking": "Available",
        "garden": "Yes",
        "flooring": "Marble",
        "view": "Monument",
        "airConditioning": "Available",
        "heating": "Central",
        "pool": "Available",
        "balcony": "Available",
        "roof": "Flat",
        "security": "Available",
        "schools": "Yes",
        "internet": "Available",
        "gym": "Not Available",
        "storage": "Available",
        "shopping": "Close",
        "hospital": "Yes",
        "park": "Yes"
    },
    {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-3.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-4.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-3.png",
    "title": "Modern Apartment in Berlin",
    "price": "$850,000",
    "description": "A sleek 3-bedroom apartment in central Berlin, featuring minimalist design and modern conveniences.",
    "address": "Berlin, Germany",
    "bedrooms": 3,
    "bathrooms": 2,
    "squareFeet": "1800",
    "yearBuilt": "2018",
    "propertyType": "Apartment",
    "country": "Germany",
    "city": "Berlin",
    "priceRange": "800,000 - 900,000",
    "squareFeetRange": "1700 - 1900 sq ft",
    "yearBuiltRange": "2015+",
    "parking": "Underground",
    "garden": "No",
    "flooring": "Tile",
    "view": "City",
    "airConditioning": "Available",
    "heating": "Radiant",
    "pool": "No",
    "balcony": "Yes",
    "roof": "Flat",
    "security": "Available",
    "schools": "Nearby",
    "internet": "Available",
    "gym": "Shared",
    "storage": "Available",
    "shopping": "Walking Distance",
    "hospital": "Yes",
    "park": "Yes"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-5.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-6.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-5.png",
    "title": "Countryside Manor in Tuscany",
    "price": "$1,800,000",
    "description": "Rustic elegance with modern touches in the heart of Tuscany, with olive groves and vineyards.",
    "address": "Tuscany, Italy",
    "bedrooms": 5,
    "bathrooms": 4,
    "squareFeet": "5000",
    "yearBuilt": "2012",
    "propertyType": "Manor",
    "country": "Italy",
    "city": "Tuscany",
    "priceRange": "1,500,000 - 2,000,000",
    "squareFeetRange": "4500 - 5500 sq ft",
    "yearBuiltRange": "2010+",
    "parking": "Available",
    "garden": "Yes",
    "flooring": "Stone",
    "view": "Countryside",
    "airConditioning": "Available",
    "heating": "Central",
    "pool": "Available",
    "balcony": "Yes",
    "roof": "Tile",
    "security": "Gated",
    "schools": "Nearby",
    "internet": "Available",
    "gym": "Private",
    "storage": "Yes",
    "shopping": "15 min drive",
    "hospital": "Yes",
    "park": "Yes"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-1.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-2.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-1.png",
    "title": "Seaside Cottage in Dubrovnik",
    "price": "$1,200,000",
    "description": "Charming stone cottage with sea views and private beach access.",
    "address": "Dubrovnik, Croatia",
    "bedrooms": 4,
    "bathrooms": 3,
    "squareFeet": "3200",
    "yearBuilt": "2015",
    "propertyType": "Cottage",
    "country": "Croatia",
    "city": "Dubrovnik",
    "priceRange": "1,000,000 - 1,500,000",
    "squareFeetRange": "3000 - 3500 sq ft",
    "yearBuiltRange": "2010+",
    "parking": "Available",
    "garden": "Yes",
    "flooring": "Wood",
    "view": "Sea",
    "airConditioning": "Available",
    "heating": "Split AC",
    "pool": "No",
    "balcony": "Yes",
    "roof": "Tile",
    "security": "Available",
    "schools": "Nearby",
    "internet": "Available",
    "gym": "No",
    "storage": "Yes",
    "shopping": "Nearby",
    "hospital": "Yes",
    "park": "Coastal Trails"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-7.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-8.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-7.png",
    "title": "Penthouse in Vienna",
    "price": "$2,100,000",
    "description": "Elegant penthouse with panoramic city views and modern European design.",
    "address": "Vienna, Austria",
    "bedrooms": 3,
    "bathrooms": 3,
    "squareFeet": "2800",
    "yearBuilt": "2021",
    "propertyType": "Penthouse",
    "country": "Austria",
    "city": "Vienna",
    "priceRange": "2,000,000 - 2,500,000",
    "squareFeetRange": "2700 - 3000 sq ft",
    "yearBuiltRange": "2020+",
    "parking": "Underground",
    "garden": "Rooftop",
    "flooring": "Hardwood",
    "view": "City",
    "airConditioning": "Available",
    "heating": "Radiant",
    "pool": "Shared",
    "balcony": "Yes",
    "roof": "Green Roof",
    "security": "High-tech",
    "schools": "Prestigious",
    "internet": "High-speed",
    "gym": "Yes",
    "storage": "Yes",
    "shopping": "Central",
    "hospital": "Nearby",
    "park": "Yes"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-9.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-10.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-9.png",
    "title": "Historic Home in Prague",
    "price": "$1,350,000",
    "description": "Beautifully restored 19th-century townhouse in the heart of Prague.",
    "address": "Prague, Czech Republic",
    "bedrooms": 4,
    "bathrooms": 3,
    "squareFeet": "4000",
    "yearBuilt": "1895",
    "propertyType": "Townhouse",
    "country": "Czech Republic",
    "city": "Prague",
    "priceRange": "1,000,000 - 1,500,000",
    "squareFeetRange": "3800 - 4200 sq ft",
    "yearBuiltRange": "Pre-1900",
    "parking": "Garage",
    "garden": "Yes",
    "flooring": "Parquet",
    "view": "Old Town",
    "airConditioning": "Available",
    "heating": "Central",
    "pool": "No",
    "balcony": "Yes",
    "roof": "Gable",
    "security": "Alarm",
    "schools": "Nearby",
    "internet": "Available",
    "gym": "No",
    "storage": "Yes",
    "shopping": "Central",
    "hospital": "Yes",
    "park": "Yes"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-11.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-12.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-11.png",
    "title": "Clifftop Villa in Algarve",
    "price": "$2,750,000",
    "description": "Breathtaking 5-bedroom villa with ocean views and a private infinity pool.",
    "address": "Algarve, Portugal",
    "bedrooms": 5,
    "bathrooms": 5,
    "squareFeet": "5200",
    "yearBuilt": "2019",
    "propertyType": "Villa",
    "country": "Portugal",
    "city": "Algarve",
    "priceRange": "2,500,000 - 3,000,000",
    "squareFeetRange": "5000 - 5500 sq ft",
    "yearBuiltRange": "2015+",
    "parking": "Garage",
    "garden": "Yes",
    "flooring": "Marble",
    "view": "Ocean",
    "airConditioning": "Available",
    "heating": "Underfloor",
    "pool": "Infinity",
    "balcony": "Yes",
    "roof": "Terracotta",
    "security": "Gated",
    "schools": "International",
    "internet": "High-speed",
    "gym": "Private",
    "storage": "Yes",
    "shopping": "Nearby",
    "hospital": "Yes",
    "park": "Coastal Walks"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-13.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-14.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-13.png",
    "title": "Scandinavian Lodge in Oslo",
    "price": "$1,600,000",
    "description": "Modern 4-bedroom lodge with nature views, large terrace, and sustainable materials.",
    "address": "Oslo, Norway",
    "bedrooms": 4,
    "bathrooms": 3,
    "squareFeet": "3600",
    "yearBuilt": "2020",
    "propertyType": "Lodge",
    "country": "Norway",
    "city": "Oslo",
    "priceRange": "1,500,000 - 2,000,000",
    "squareFeetRange": "3500 - 3700 sq ft",
    "yearBuiltRange": "2020+",
    "parking": "Covered",
    "garden": "Yes",
    "flooring": "Wood",
    "view": "Forest",
    "airConditioning": "Available",
    "heating": "Geothermal",
    "pool": "Hot Tub",
    "balcony": "Yes",
    "roof": "Green Roof",
    "security": "Smart System",
    "schools": "Nearby",
    "internet": "Fiber",
    "gym": "No",
    "storage": "Yes",
    "shopping": "15 min",
    "hospital": "Yes",
    "park": "Nearby"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-15.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-16.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-15.png",
    "title": "Modern Duplex in Barcelona",
    "price": "$950,000",
    "description": "Bright and open 3-bedroom duplex in Barcelona's Eixample district, near shops and cafes.",
    "address": "Barcelona, Spain",
    "bedrooms": 3,
    "bathrooms": 2,
    "squareFeet": "2000",
    "yearBuilt": "2016",
    "propertyType": "Duplex",
    "country": "Spain",
    "city": "Barcelona",
    "priceRange": "900,000 - 1,000,000",
    "squareFeetRange": "1900 - 2100 sq ft",
    "yearBuiltRange": "2015+",
    "parking": "Street",
    "garden": "Shared Courtyard",
    "flooring": "Hardwood",
    "view": "Street",
    "airConditioning": "Available",
    "heating": "Central",
    "pool": "Shared",
    "balcony": "Yes",
    "roof": "Flat",
    "security": "Yes",
    "schools": "Nearby",
    "internet": "Available",
    "gym": "Shared",
    "storage": "Yes",
    "shopping": "Walking Distance",
    "hospital": "Yes",
    "park": "Yes"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-17.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-18.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-17.png",
    "title": "Château Estate in Bordeaux",
    "price": "$3,900,000",
    "description": "Historic château with vineyard estate and guest cottages in Bordeaux's wine country.",
    "address": "Bordeaux, France",
    "bedrooms": 8,
    "bathrooms": 6,
    "squareFeet": "12000",
    "yearBuilt": "1870",
    "propertyType": "Château",
    "country": "France",
    "city": "Bordeaux",
    "priceRange": "3,500,000 - 4,000,000",
    "squareFeetRange": "11000 - 13000 sq ft",
    "yearBuiltRange": "Pre-1900",
    "parking": "Private",
    "garden": "Extensive",
    "flooring": "Stone & Wood",
    "view": "Vineyard",
    "airConditioning": "Partial",
    "heating": "Radiator",
    "pool": "Yes",
    "balcony": "Multiple",
    "roof": "Sloped",
    "security": "Gated",
    "schools": "Private Options",
    "internet": "Available",
    "gym": "Private",
    "storage": "Yes",
    "shopping": "15 min",
    "hospital": "Yes",
    "park": "Private Grounds"
  },
  {
    "imgUrl": "https://julius-altmann-3333.github.io/website-images/real-estate-19.png",
    "imgUrl2": "https://julius-altmann-3333.github.io/website-images/real-estate-20.png",
    "imgUrl3": "https://julius-altmann-3333.github.io/website-images/real-estate-19.png",
    "title": "Lake House in Zurich",
    "price": "$2,300,000",
    "description": "Stylish lakefront property with 4 bedrooms and stunning views of Lake Zurich.",
    "address": "Zurich, Switzerland",
    "bedrooms": 4,
    "bathrooms": 3,
    "squareFeet": "4300",
    "yearBuilt": "2017",
    "propertyType": "House",
    "country": "Switzerland",
    "city": "Zurich",
    "priceRange": "2,000,000 - 2,500,000",
    "squareFeetRange": "4200 - 4500 sq ft",
    "yearBuiltRange": "2015+",
    "parking": "Garage",
    "garden": "Yes",
    "flooring": "Engineered Wood",
    "view": "Lake",
    "airConditioning": "Available",
    "heating": "Underfloor",
    "pool": "No",
    "balcony": "Yes",
    "roof": "Modern Flat",
    "security": "Advanced",
    "schools": "Yes",
    "internet": "Fiber",
    "gym": "Yes",
    "storage": "Yes",
    "shopping": "Close",
    "hospital": "Nearby",
    "park": "Lake Promenade"
  }
];
