const realEstateData = [
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Luxury Apartment in Lagos",
        price: "$750,000",
        description: "A modern 4-bedroom apartment in Victoria Island with ocean views.",
        address: "Victoria Island, Lagos, Nigeria",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "3200",
        yearBuilt: "2022",
        propertyType: "Apartment",
        country: "Nigeria",
        city: "Lagos",
        priceRange: "700,000 - 800,000",
        squareFeetRange: "3000 - 3500 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Marble",
        view: "Ocean",
        airConditioning: "Available",
        heating: "None",
        pool: "Available",
        balcony: "Available",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Available",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Townhouse in Nairobi",
        price: "$420,000",
        description: "Spacious 3-bedroom townhouse in Karen with a private garden.",
        address: "Karen, Nairobi, Kenya",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2800",
        yearBuilt: "2021",
        propertyType: "Townhouse",
        country: "Kenya",
        city: "Nairobi",
        priceRange: "400,000 - 450,000",
        squareFeetRange: "2500 - 3000 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Yes",
        flooring: "Wood",
        view: "Garden",
        airConditioning: "Available",
        heating: "Available",
        pool: "Not Available",
        balcony: "Yes",
        roof: "Gable",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Seaside Villa in Cape Town",
        price: "$1,200,000",
        description: "Elegant 5-bedroom villa in Camps Bay with stunning mountain and sea views.",
        address: "Camps Bay, Cape Town, South Africa",
        bedrooms: 5,
        bathrooms: 4,
        squareFeet: "4500",
        yearBuilt: "2019",
        propertyType: "Villa",
        country: "South Africa",
        city: "Cape Town",
        priceRange: "1,000,000 - 1,500,000",
        squareFeetRange: "4000 - 5000 sq ft",
        yearBuiltRange: "2015 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Hardwood",
        view: "Mountain & Sea",
        airConditioning: "Available",
        heating: "Central",
        pool: "Available",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Modern Flat in Cairo",
        price: "$300,000",
        description: "Newly built 2-bedroom flat in New Cairo with modern facilities.",
        address: "New Cairo, Cairo, Egypt",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1600",
        yearBuilt: "2023",
        propertyType: "Apartment",
        country: "Egypt",
        city: "Cairo",
        priceRange: "250,000 - 350,000",
        squareFeetRange: "1500 - 1700 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "City",
        airConditioning: "Available",
        heating: "Available",
        pool: "Not Available",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "No",
        shopping: "Nearby",
        hospital: "Yes",
        park: "No"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Executive Home in Accra",
        price: "$600,000",
        description: "An upscale 4-bedroom home in East Legon with landscaped garden and pool.",
        address: "East Legon, Accra, Ghana",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "3600",
        yearBuilt: "2021",
        propertyType: "House",
        country: "Ghana",
        city: "Accra",
        priceRange: "550,000 - 650,000",
        squareFeetRange: "3500 - 3700 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Yes",
        flooring: "Tile",
        view: "Garden",
        airConditioning: "Available",
        heating: "None",
        pool: "Available",
        balcony: "Yes",
        roof: "Gable",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Family House in Addis Ababa",
        price: "$350,000",
        description: "Comfortable 3-bedroom home in Bole with traditional touches and modern finishes.",
        address: "Bole, Addis Ababa, Ethiopia",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2700",
        yearBuilt: "2020",
        propertyType: "House",
        country: "Ethiopia",
        city: "Addis Ababa",
        priceRange: "300,000 - 400,000",
        squareFeetRange: "2500 - 3000 sq ft",
        yearBuiltRange: "2019 - 2021",
        parking: "Available",
        garden: "Yes",
        flooring: "Laminate",
        view: "City",
        airConditioning: "Not Available",
        heating: "Available",
        pool: "Not Available",
        balcony: "No",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Contemporary Apartment in Dakar",
        price: "$280,000",
        description: "2-bedroom apartment in Almadies close to the beach with stylish interior.",
        address: "Almadies, Dakar, Senegal",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1500",
        yearBuilt: "2022",
        propertyType: "Apartment",
        country: "Senegal",
        city: "Dakar",
        priceRange: "250,000 - 300,000",
        squareFeetRange: "1400 - 1600 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "Sea",
        airConditioning: "Available",
        heating: "Not Available",
        pool: "Available",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Available",
        storage: "No",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Penthouse in Casablanca",
        price: "$800,000",
        description: "Elegant penthouse in Maarif district with panoramic city views and high-end finishes.",
        address: "Maarif, Casablanca, Morocco",
        bedrooms: 3,
        bathrooms: 3,
        squareFeet: "3500",
        yearBuilt: "2021",
        propertyType: "Penthouse",
        country: "Morocco",
        city: "Casablanca",
        priceRange: "750,000 - 850,000",
        squareFeetRange: "3300 - 3700 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Marble",
        view: "City",
        airConditioning: "Available",
        heating: "Available",
        pool: "Yes",
        balcony: "Yes",
        roof: "Terrace",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Modern House in Kampala",
        price: "$380,000",
        description: "4-bedroom house in Kololo, a serene neighborhood with greenery.",
        address: "Kololo, Kampala, Uganda",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "3000",
        yearBuilt: "2019",
        propertyType: "House",
        country: "Uganda",
        city: "Kampala",
        priceRange: "350,000 - 400,000",
        squareFeetRange: "2800 - 3100 sq ft",
        yearBuiltRange: "2018 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Wood",
        view: "Garden",
        airConditioning: "Available",
        heating: "None",
        pool: "Not Available",
        balcony: "Yes",
        roof: "Sloped",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Beachside Bungalow in Dar es Salaam",
        price: "$450,000",
        description: "Charming 3-bedroom bungalow near Msasani beach with tropical vibe.",
        address: "Msasani, Dar es Salaam, Tanzania",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2800",
        yearBuilt: "2020",
        propertyType: "Bungalow",
        country: "Tanzania",
        city: "Dar es Salaam",
        priceRange: "400,000 - 500,000",
        squareFeetRange: "2700 - 2900 sq ft",
        yearBuiltRange: "2019 - 2021",
        parking: "Available",
        garden: "Yes",
        flooring: "Tile",
        view: "Beach",
        airConditioning: "Available",
        heating: "Not Available",
        pool: "No",
        balcony: "Yes",
        roof: "Thatched",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    }
];
