const realEstateData = [
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Penthouse in Manhattan",
        price: "$3,200,000",
        description: "A luxury 3-bedroom penthouse with skyline views of NYC and high-end interiors.",
        address: "Manhattan, New York City, USA",
        bedrooms: 3,
        bathrooms: 3,
        squareFeet: "2200",
        yearBuilt: "2021",
        propertyType: "Penthouse",
        country: "USA",
        city: "New York City",
        priceRange: "3,000,000 - 3,500,000",
        squareFeetRange: "2100 - 2300 sq ft",
        yearBuiltRange: "2020+",
        parking: "Not Available",
        garden: "No",
        flooring: "Hardwood",
        view: "Skyline",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Terrace",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Very Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Contemporary Villa in Beverly Hills",
        price: "$4,500,000",
        description: "A 5-bedroom contemporary estate with a pool and panoramic views in Los Angeles.",
        address: "Beverly Hills, Los Angeles, USA",
        bedrooms: 5,
        bathrooms: 6,
        squareFeet: "6000",
        yearBuilt: "2022",
        propertyType: "Villa",
        country: "USA",
        city: "Los Angeles",
        priceRange: "4,000,000 - 5,000,000",
        squareFeetRange: "5800 - 6200 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Yes",
        flooring: "Marble",
        view: "Hills",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Downtown Condo in Toronto",
        price: "$950,000",
        description: "Stylish 2-bedroom condo in Downtown Toronto with CN Tower views.",
        address: "Downtown, Toronto, Canada",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1300",
        yearBuilt: "2019",
        propertyType: "Condo",
        country: "Canada",
        city: "Toronto",
        priceRange: "900,000 - 1,000,000",
        squareFeetRange: "1200 - 1400 sq ft",
        yearBuiltRange: "2018 - 2020",
        parking: "Available",
        garden: "No",
        flooring: "Hardwood",
        view: "City",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Waterfront Apartment in Vancouver",
        price: "$1,300,000",
        description: "Luxury 2-bedroom waterfront apartment in Coal Harbour with marina views.",
        address: "Coal Harbour, Vancouver, Canada",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1400",
        yearBuilt: "2021",
        propertyType: "Apartment",
        country: "Canada",
        city: "Vancouver",
        priceRange: "1,200,000 - 1,400,000",
        squareFeetRange: "1300 - 1500 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Engineered Wood",
        view: "Waterfront",
        airConditioning: "Available",
        heating: "Radiant",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Colonial House in Mexico City",
        price: "$600,000",
        description: "Beautifully restored colonial house with garden in Coyoacán, Mexico City.",
        address: "Coyoacán, Mexico City, Mexico",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "2800",
        yearBuilt: "Renovated 2020",
        propertyType: "House",
        country: "Mexico",
        city: "Mexico City",
        priceRange: "550,000 - 650,000",
        squareFeetRange: "2700 - 2900 sq ft",
        yearBuiltRange: "Renovated",
        parking: "Available",
        garden: "Yes",
        flooring: "Tile",
        view: "Garden",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "No",
        balcony: "Yes",
        roof: "Terracotta",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Oceanfront Condo in Miami",
        price: "$1,700,000",
        description: "Modern 3-bedroom condo in South Beach with direct ocean views and private balcony.",
        address: "South Beach, Miami, USA",
        bedrooms: 3,
        bathrooms: 3,
        squareFeet: "2000",
        yearBuilt: "2022",
        propertyType: "Condo",
        country: "USA",
        city: "Miami",
        priceRange: "1,600,000 - 1,800,000",
        squareFeetRange: "1900 - 2100 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "Ocean",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Tech Loft in San Francisco",
        price: "$1,200,000",
        description: "Modern 2-bedroom loft in SoMa, perfect for tech professionals with open-plan living.",
        address: "SoMa, San Francisco, USA",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1500",
        yearBuilt: "2021",
        propertyType: "Loft",
        country: "USA",
        city: "San Francisco",
        priceRange: "1,100,000 - 1,300,000",
        squareFeetRange: "1400 - 1600 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Concrete",
        view: "Urban",
        airConditioning: "Available",
        heating: "Central",
        pool: "No",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Duplex in Old Montreal",
        price: "$780,000",
        description: "Charming 2-story duplex with historical charm and modern upgrades.",
        address: "Old Montreal, Montreal, Canada",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "1800",
        yearBuilt: "Renovated 2018",
        propertyType: "Duplex",
        country: "Canada",
        city: "Montreal",
        priceRange: "750,000 - 800,000",
        squareFeetRange: "1700 - 1900 sq ft",
        yearBuiltRange: "Renovated",
        parking: "Not Available",
        garden: "No",
        flooring: "Wood",
        view: "Old Town",
        airConditioning: "Available",
        heating: "Radiators",
        pool: "No",
        balcony: "Yes",
        roof: "Pitched",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Downtown Apartment in Chicago",
        price: "$890,000",
        description: "Spacious 3-bedroom high-rise apartment with views of Lake Michigan.",
        address: "Downtown, Chicago, USA",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2000",
        yearBuilt: "2020",
        propertyType: "Apartment",
        country: "USA",
        city: "Chicago",
        priceRange: "850,000 - 900,000",
        squareFeetRange: "1900 - 2100 sq ft",
        yearBuiltRange: "2019 - 2021",
        parking: "Available",
        garden: "No",
        flooring: "Hardwood",
        view: "Lake",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Very Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Beachfront Villa in Nassau",
        price: "$2,100,000",
        description: "Tropical 4-bedroom villa on the beach with infinity pool and private dock.",
        address: "Cable Beach, Nassau, Bahamas",
        bedrooms: 4,
        bathrooms: 4,
        squareFeet: "3500",
        yearBuilt: "2021",
        propertyType: "Villa",
        country: "Bahamas",
        city: "Nassau",
        priceRange: "2,000,000 - 2,200,000",
        squareFeetRange: "3400 - 3600 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Yes",
        flooring: "Stone",
        view: "Ocean",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "Yes",
        balcony: "Yes",
        roof: "Tile",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Beachfront"
    }
];
