const realEstateData = [
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Modern Condo in Tokyo",
        price: "$950,000",
        description: "Sleek 2-bedroom condo in Shibuya with cityscape views and smart home features.",
        address: "Shibuya, Tokyo, Japan",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1200",
        yearBuilt: "2021",
        propertyType: "Condo",
        country: "Japan",
        city: "Tokyo",
        priceRange: "900,000 - 1,000,000",
        squareFeetRange: "1100 - 1300 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Wood",
        view: "City",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Luxury Apartment in Seoul",
        price: "$820,000",
        description: "High-rise apartment in Gangnam with 3 bedrooms and excellent amenities.",
        address: "Gangnam, Seoul, South Korea",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "1500",
        yearBuilt: "2020",
        propertyType: "Apartment",
        country: "South Korea",
        city: "Seoul",
        priceRange: "800,000 - 850,000",
        squareFeetRange: "1400 - 1600 sq ft",
        yearBuiltRange: "2019 - 2021",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "Skyline",
        airConditioning: "Available",
        heating: "Floor Heating",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Penthouse in Bangkok",
        price: "$680,000",
        description: "Elegant 3-bedroom penthouse near Sukhumvit with river view and rooftop pool.",
        address: "Sukhumvit, Bangkok, Thailand",
        bedrooms: 3,
        bathrooms: 3,
        squareFeet: "2200",
        yearBuilt: "2022",
        propertyType: "Penthouse",
        country: "Thailand",
        city: "Bangkok",
        priceRange: "650,000 - 700,000",
        squareFeetRange: "2000 - 2300 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Marble",
        view: "River",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "Yes",
        balcony: "Yes",
        roof: "Terrace",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "City Loft in Singapore",
        price: "$1,200,000",
        description: "Stylish 2-bedroom loft in Marina Bay with premium city amenities and views.",
        address: "Marina Bay, Singapore",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1300",
        yearBuilt: "2023",
        propertyType: "Loft",
        country: "Singapore",
        city: "Singapore",
        priceRange: "1,100,000 - 1,300,000",
        squareFeetRange: "1200 - 1400 sq ft",
        yearBuiltRange: "2022+",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "Marina",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Very Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Luxury Villa in Dubai",
        price: "$2,800,000",
        description: "Sprawling 5-bedroom villa in Palm Jumeirah with private beach access.",
        address: "Palm Jumeirah, Dubai, UAE",
        bedrooms: 5,
        bathrooms: 5,
        squareFeet: "7000",
        yearBuilt: "2021",
        propertyType: "Villa",
        country: "UAE",
        city: "Dubai",
        priceRange: "2,500,000 - 3,000,000",
        squareFeetRange: "6500 - 7500 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Yes",
        flooring: "Marble",
        view: "Sea",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Luxury Mall Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "High-Rise Apartment in Mumbai",
        price: "$700,000",
        description: "3-bedroom apartment in South Mumbai with panoramic Arabian Sea views.",
        address: "South Mumbai, Mumbai, India",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "1800",
        yearBuilt: "2022",
        propertyType: "Apartment",
        country: "India",
        city: "Mumbai",
        priceRange: "650,000 - 750,000",
        squareFeetRange: "1700 - 1900 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "Sea",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Condo in Kuala Lumpur",
        price: "$400,000",
        description: "Chic 2-bedroom condo in KLCC area with skyline views and rooftop amenities.",
        address: "KLCC, Kuala Lumpur, Malaysia",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1400",
        yearBuilt: "2020",
        propertyType: "Condo",
        country: "Malaysia",
        city: "Kuala Lumpur",
        priceRange: "380,000 - 420,000",
        squareFeetRange: "1300 - 1500 sq ft",
        yearBuiltRange: "2019 - 2021",
        parking: "Available",
        garden: "No",
        flooring: "Wood",
        view: "City",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Family House in Jakarta",
        price: "$350,000",
        description: "Spacious 3-bedroom home in South Jakarta with a garden and modern layout.",
        address: "South Jakarta, Jakarta, Indonesia",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2400",
        yearBuilt: "2019",
        propertyType: "House",
        country: "Indonesia",
        city: "Jakarta",
        priceRange: "320,000 - 380,000",
        squareFeetRange: "2300 - 2500 sq ft",
        yearBuiltRange: "2018 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Tile",
        view: "Garden",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "No",
        balcony: "Yes",
        roof: "Sloped",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Luxury Residence in Shanghai",
        price: "$1,100,000",
        description: "Elegant 4-bedroom apartment in Pudong with skyline and river views.",
        address: "Pudong, Shanghai, China",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "2500",
        yearBuilt: "2021",
        propertyType: "Apartment",
        country: "China",
        city: "Shanghai",
        priceRange: "1,000,000 - 1,200,000",
        squareFeetRange: "2400 - 2600 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Marble",
        view: "River & Skyline",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Nearby"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Colonial Villa in Hanoi",
        price: "$480,000",
        description: "3-bedroom restored colonial-style villa in the French Quarter of Hanoi.",
        address: "French Quarter, Hanoi, Vietnam",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2100",
        yearBuilt: "Renovated 2020",
        propertyType: "Villa",
        country: "Vietnam",
        city: "Hanoi",
        priceRange: "450,000 - 500,000",
        squareFeetRange: "2000 - 2200 sq ft",
        yearBuiltRange: "Renovated 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Wood",
        view: "Courtyard",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "No",
        balcony: "Yes",
        roof: "Colonial",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    }
];
