const realEstateData = [
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Harbourfront Luxury in Sydney",
        price: "$2,300,000",
        description: "Elegant 4-bedroom apartment overlooking Sydney Harbour with floor-to-ceiling windows.",
        address: "Circular Quay, Sydney, Australia",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "2800",
        yearBuilt: "2021",
        propertyType: "Apartment",
        country: "Australia",
        city: "Sydney",
        priceRange: "2,000,000 - 2,500,000",
        squareFeetRange: "2700 - 2900 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Hardwood",
        view: "Harbour",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Modern Townhouse in Melbourne",
        price: "$980,000",
        description: "3-bedroom townhouse in Fitzroy with sleek design and rooftop terrace.",
        address: "Fitzroy, Melbourne, Australia",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2000",
        yearBuilt: "2020",
        propertyType: "Townhouse",
        country: "Australia",
        city: "Melbourne",
        priceRange: "900,000 - 1,000,000",
        squareFeetRange: "1900 - 2100 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Small",
        flooring: "Polished Concrete",
        view: "Urban",
        airConditioning: "Available",
        heating: "Central",
        pool: "No",
        balcony: "Yes",
        roof: "Terrace",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Waterfront Home in Auckland",
        price: "$1,500,000",
        description: "Beautiful 5-bedroom home with direct access to the bay and private dock.",
        address: "Devonport, Auckland, New Zealand",
        bedrooms: 5,
        bathrooms: 4,
        squareFeet: "3000",
        yearBuilt: "2019",
        propertyType: "House",
        country: "New Zealand",
        city: "Auckland",
        priceRange: "1,400,000 - 1,600,000",
        squareFeetRange: "2900 - 3100 sq ft",
        yearBuiltRange: "2018 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Wood",
        view: "Bay",
        airConditioning: "Available",
        heating: "Radiant",
        pool: "Yes",
        balcony: "Yes",
        roof: "Gabled",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Hillside Retreat in Wellington",
        price: "$870,000",
        description: "Charming 4-bedroom house with panoramic views of Wellington Harbour.",
        address: "Kelburn, Wellington, New Zealand",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "2200",
        yearBuilt: "2017",
        propertyType: "House",
        country: "New Zealand",
        city: "Wellington",
        priceRange: "800,000 - 900,000",
        squareFeetRange: "2100 - 2300 sq ft",
        yearBuiltRange: "2015 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Carpet & Tile",
        view: "Harbour",
        airConditioning: "Available",
        heating: "Radiant",
        pool: "No",
        balcony: "Yes",
        roof: "Gabled",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Contemporary Apartment in Brisbane",
        price: "$720,000",
        description: "2-bedroom apartment in South Bank with river views and rooftop pool.",
        address: "South Bank, Brisbane, Australia",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1400",
        yearBuilt: "2022",
        propertyType: "Apartment",
        country: "Australia",
        city: "Brisbane",
        priceRange: "700,000 - 750,000",
        squareFeetRange: "1300 - 1500 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Laminate",
        view: "River",
        airConditioning: "Available",
        heating: "Central",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Coastal Villa in Perth",
        price: "$1,050,000",
        description: "3-bedroom coastal villa with private beach access in Cottesloe.",
        address: "Cottesloe, Perth, Australia",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "2400",
        yearBuilt: "2021",
        propertyType: "Villa",
        country: "Australia",
        city: "Perth",
        priceRange: "1,000,000 - 1,100,000",
        squareFeetRange: "2300 - 2500 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "Yes",
        flooring: "Tile",
        view: "Ocean",
        airConditioning: "Available",
        heating: "Split System",
        pool: "Yes",
        balcony: "Yes",
        roof: "Sloped",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Close",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Heritage Home in Adelaide",
        price: "$890,000",
        description: "Renovated Victorian-style house with modern amenities and spacious backyard.",
        address: "Norwood, Adelaide, Australia",
        bedrooms: 4,
        bathrooms: 3,
        squareFeet: "2600",
        yearBuilt: "1900 (renovated 2020)",
        propertyType: "Heritage Home",
        country: "Australia",
        city: "Adelaide",
        priceRange: "850,000 - 900,000",
        squareFeetRange: "2500 - 2700 sq ft",
        yearBuiltRange: "Renovated",
        parking: "Available",
        garden: "Yes",
        flooring: "Wood & Tile",
        view: "Garden",
        airConditioning: "Available",
        heating: "Central",
        pool: "No",
        balcony: "Yes",
        roof: "Gabled",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Tropical House in Suva",
        price: "$430,000",
        description: "3-bedroom tropical home surrounded by greenery and close to the ocean.",
        address: "Tamavua, Suva, Fiji",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "1800",
        yearBuilt: "2018",
        propertyType: "House",
        country: "Fiji",
        city: "Suva",
        priceRange: "400,000 - 450,000",
        squareFeetRange: "1700 - 1900 sq ft",
        yearBuiltRange: "2015 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Tile",
        view: "Tropical Garden",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "No",
        balcony: "Yes",
        roof: "Sloped",
        security: "Available",
        schools: "Nearby",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Hilltop Home in Port Moresby",
        price: "$380,000",
        description: "Private 3-bedroom home on a hillside with sweeping city views.",
        address: "Waigani, Port Moresby, Papua New Guinea",
        bedrooms: 3,
        bathrooms: 2,
        squareFeet: "1700",
        yearBuilt: "2016",
        propertyType: "House",
        country: "Papua New Guinea",
        city: "Port Moresby",
        priceRange: "350,000 - 400,000",
        squareFeetRange: "1600 - 1800 sq ft",
        yearBuiltRange: "2015 - 2020",
        parking: "Available",
        garden: "Yes",
        flooring: "Concrete",
        view: "City",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "No",
        balcony: "Yes",
        roof: "Sloped",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "No",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    },
    {
        imgUrl: "https://via.placeholder.com/250",
        title: "Coastal Apartment in Nouméa",
        price: "$610,000",
        description: "Modern 2-bedroom apartment near Anse Vata Beach with sea breeze and pool access.",
        address: "Anse Vata, Nouméa, New Caledonia",
        bedrooms: 2,
        bathrooms: 2,
        squareFeet: "1500",
        yearBuilt: "2020",
        propertyType: "Apartment",
        country: "New Caledonia",
        city: "Nouméa",
        priceRange: "600,000 - 650,000",
        squareFeetRange: "1400 - 1600 sq ft",
        yearBuiltRange: "2020+",
        parking: "Available",
        garden: "No",
        flooring: "Tile",
        view: "Sea",
        airConditioning: "Available",
        heating: "Not Required",
        pool: "Yes",
        balcony: "Yes",
        roof: "Flat",
        security: "Available",
        schools: "Yes",
        internet: "Available",
        gym: "Yes",
        storage: "Yes",
        shopping: "Nearby",
        hospital: "Yes",
        park: "Yes"
    }
];
